name: Dokka Documentation

on:
  push:
    branches:
      - foo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build dokka HTML dokumentation
        working-directory: watermarker
        run: ./gradlew dokkaHtml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
#          deploy_key: ${{ secrets.DEP_KEY_SECRET }}
          publish_dir: ./watermarker/build/dokka/html
          publish_branch: gh-pages

